name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@0f6c180522d02d9e608096c4dcf3b691193b4d44
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
